name: HIFINI auto sign

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'  # 0:00 GMT+8 is 16:00 GMT

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Change this to your Python version if needed

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install requests

      - name: Run Python script
        env:
          COOKIE: ${{ secrets.cookies }}
        run: python hifini_auto_sign.py
