name: test

on:
  schedule:
    - cron: '* * * * *'  # 0:00 GMT+8 is 16:00 GMT
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          echo "test"
